server:
  port: 8080

spring:
  datasource:
    password: password
    url: jdbc:postgresql://localhost:5432/marlonbarbearia
    username: ramagalhaes
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create-drop
      dialect: org.hibernate.dialect.PostgreSQLDialect
jwt:
  secret:
    expiration: 6000000000
    encoder: 6b656A&456-2be%$9-4e59-817b*!-7c3Q&@37fba1bc