server:
  port: 8080

spring:
  datasource:
    password: password
    url: jdbc:postgresql://localhost:5432/marlonbarbearia
    username: ramagalhaes
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create-drop
      dialect: org.hibernate.dialect.PostgreSQLDialect