server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create
  h2:
    console:
      path: /h2-console
      enabled: true